name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  ruff:
    name: Format and lint
    uses: kellen-miller/ci/.github/workflows/python-lint.yaml@d1c91763535a5866b55282018f301d921b22bcd5

  yamllint:
    name: YAML lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0

      - name: Lint YAML
        run: uv run --locked yamllint --strict .
